# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
