# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trial',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
